import{useEffect,useMemo,useRef,useState}from'react';
import{Alert,ActivityIndicator,FlatList,Linking,Pressable,StyleSheet,Text,TextInput,View}from'react-native';
import{useLocalSearchParams}from'expo-router';
import{useQueryClient}from'@tanstack/react-query';
import{supabase}from'../../src/data/supabase';
import{useBookings,useCancelBooking,useCompleteBooking,useConfirmBooking,useMarkMessagesRead,useMessages,useProposeBookingTime,useRespondBookingTime,useProfile,useSendMessage,useSetBookingMeetingLink}from'../../src/hooks/useCoreData';
import{Page}from'../../src/ui/layout';
import{ErrorState}from'../../src/ui/components';
import{theme}from'../../src/ui/theme';

export default function Message(){
 const{id}=useLocalSearchParams<{id:string}>();const qc=useQueryClient();const profile=useProfile();const role=profile.data?.role==='guruba'?'guruba':'client';const bookings=useBookings(role);const q=useMessages(id);const send=useSendMessage();const mark=useMarkMessagesRead();const confirm=useConfirmBooking();const respond=useRespondBookingTime();const propose=useProposeBookingTime();const cancel=useCancelBooking();const complete=useCompleteBooking();const meeting=useSetBookingMeetingLink();
 const[text,setText]=useState('');const[proposal,setProposal]=useState('');const[showProposal,setShowProposal]=useState(false);const[link,setLink]=useState('');const[showLink,setShowLink]=useState(false);const marked=useRef(new Set<string>());
 const activeBooking=useMemo(()=>{const rows=(bookings.data??[]).filter(b=>!['completed','cancelled'].includes(b.status));const matches=rows.filter(b=>role==='client'?b.gurubas?.user_id===id:b.user_id===id);return matches.sort((a,b)=>new Date(a.scheduled_at??a.proposed_time??a.created_at??0).getTime()-new Date(b.scheduled_at??b.proposed_time??b.created_at??0).getTime())[0]??null},[bookings.data,role,id]);
 useEffect(()=>{const unread=(q.data??[]).filter(x=>!x.is_read&&!marked.current.has(x.id)).map(x=>x.id);if(unread.length){unread.forEach(x=>marked.current.add(x));mark.mutate(unread)}},[q.data]);
 useEffect(()=>{if(!id)return;const ch=supabase.channel('purohit-chat-'+id).on('postgres_changes',{event:'*',schema:'public',table:'messages'},()=>{q.refetch();bookings.refetch();qc.invalidateQueries({queryKey:['message-users']})}).subscribe();return()=>{supabase.removeChannel(ch)}},[id]);
 async function act(fn:()=>Promise<unknown>,ok:string){try{await fn();Alert.alert('Done',ok);await Promise.all([q.refetch(),bookings.refetch()])}catch(e:any){Alert.alert('Action failed',e?.message??'Please try again.')}}
 async function submit(){const value=text.trim();if(!value||send.isPending)return;try{await send.mutateAsync({receiverId:id,content:value,bookingId:activeBooking?.id});setText('')}catch{}}
 async function submitProposal(){const value=proposal.trim();const m=value.match(/^(\d{4})-(\d{2})-(\d{2})[T ](\d{2}):(\d{2})$/);if(!activeBooking||!m){Alert.alert('Invalid time','Use YYYY-MM-DD HH:mm in Nepal time.');return}const[,y,mo,d,h,mi]=m.map(Number);const iso=new Date(Date.UTC(y,mo-1,d,h,mi)-20700*1000).toISOString();if(new Date(iso)<=new Date()){Alert.alert('Invalid time','Choose a future time.');return}await act(()=>propose.mutateAsync({id:activeBooking.id,at:iso,deadline:new Date(Date.now()+3600000).toISOString()}),'Time proposal sent to the client.');setProposal('');setShowProposal(false)}
 async function submitLink(){let value=link.trim();if(value.startsWith('wa.me/'))value='https://'+value;if(!activeBooking||!/^https?:\/\/\S+$/i.test(value)){Alert.alert('Invalid link','Use a full https:// meeting URL.');return}await act(()=>meeting.mutateAsync({id:activeBooking.id,link:value}),'Meeting link saved.');setLink('');setShowLink(false)}
 const bookingActions=activeBooking?<View style={s.actions}>
  {role==='client'&&activeBooking.status==='awaiting_client_confirmation'?<><Action label="Accept proposed time" onPress={()=>act(()=>respond.mutateAsync({id:activeBooking.id,accept:true}),'Proposed time accepted.')}/><Action label="Reject / cancel" secondary onPress={()=>Alert.alert('Cancel booking','Reject this proposed time and cancel the booking?',[{text:'Keep'},{text:'Cancel',style:'destructive',onPress:()=>act(()=>cancel.mutateAsync(activeBooking.id),'Booking cancelled.')}])}/></>:null}
  {role==='guruba'&&activeBooking.status==='pending'?<><Action label="Accept booking" onPress={()=>act(()=>confirm.mutateAsync(activeBooking.id),'Booking accepted.')}/><Action label="Propose time" secondary onPress={()=>setShowProposal(true)}/><Action label="Decline" secondary onPress={()=>Alert.alert('Decline booking','Cancel this booking request?',[{text:'Keep'},{text:'Decline',style:'destructive',onPress:()=>act(()=>cancel.mutateAsync(activeBooking.id),'Booking declined.')}])}/></>:null}
  {role==='guruba'&&activeBooking.status==='awaiting_client_confirmation'?<Text style={s.waiting}>Waiting for client confirmation.</Text>:null}
  {activeBooking.status==='confirmed'?<>
    {role==='guruba'?<Action label={activeBooking.meeting_link?'Edit meeting link':'Add meeting link'} secondary onPress={()=>{setLink(activeBooking.meeting_link??'');setShowLink(true)}}/>:null}
    {role==='guruba'?<Action label="Mark completed" onPress={()=>{if(activeBooking.scheduled_at&&new Date(activeBooking.scheduled_at)>new Date()){Alert.alert('Too early','This booking cannot be completed before its scheduled time.');return}act(()=>complete.mutateAsync(activeBooking.id),'Booking marked completed.')}}/>:null}
    {role==='client'&&activeBooking.meeting_link?<Action label="Join meeting" onPress={()=>Linking.openURL(activeBooking.meeting_link!)}/>:null}
    <Action label="Cancel booking" secondary onPress={()=>Alert.alert('Cancel booking','Cancel this confirmed booking?',[{text:'Keep'},{text:'Cancel',style:'destructive',onPress:()=>act(()=>cancel.mutateAsync(activeBooking.id),'Booking cancelled.')}])}/>
  </>:null}
  {role==='guruba'&&activeBooking.status==='rescheduled'?<Action label="Mark completed" onPress={()=>act(()=>complete.mutateAsync(activeBooking.id),'Booking marked completed.')}/>:null}
 </View>:null;

 if(q.isLoading||profile.isLoading)return <View style={s.center}><ActivityIndicator/></View>;
 if(q.isError)return <Page><ErrorState title="Unable to load conversation" onRetry={q.refetch}/></Page>;
 return <Page><View style={s.wrap}>
  <View style={s.header}><Text style={s.title}>Conversation</Text><Text style={s.sub}>{role==='guruba'?'Guruba':'Client'}</Text></View>
  {activeBooking?<View style={s.booking}><View style={s.row}><View style={{flex:1}}><Text style={s.bookingTitle}>{activeBooking.services?.title??'Booking'}</Text><Text style={s.meta}>{activeBooking.status.replaceAll('_',' ')}</Text></View><Text style={s.meta}>{activeBooking.is_online?'Online':'In person'}</Text></View><Text style={s.meta}>Time: {new Date(activeBooking.scheduled_at??activeBooking.proposed_time??0).toLocaleString()}</Text>{activeBooking.location_address?<Text style={s.meta}>Location: {activeBooking.location_address}</Text>:null}{activeBooking.booking_note?<Text style={s.note}>{activeBooking.booking_note}</Text>:null}{bookingActions}</View>:null}
  {showProposal?<View style={s.editor}><Text style={s.editorTitle}>Propose a new time</Text><Text style={s.meta}>Nepal time: YYYY-MM-DD HH:mm</Text><TextInput value={proposal} onChangeText={setProposal} placeholder="2026-10-08 10:30" style={s.input}/><View style={s.actions}><Action label="Send proposal" onPress={submitProposal}/><Action label="Cancel" secondary onPress={()=>setShowProposal(false)}/></View></View>:null}
  {showLink?<View style={s.editor}><Text style={s.editorTitle}>Meeting link</Text><TextInput autoCapitalize="none" keyboardType="url" value={link} onChangeText={setLink} placeholder="https://meet.google.com/..." style={s.input}/><View style={s.actions}><Action label="Save link" onPress={submitLink}/><Action label="Cancel" secondary onPress={()=>setShowLink(false)}/></View></View>:null}
  <FlatList style={s.messages} contentContainerStyle={s.messageList} data={q.data??[]} keyExtractor={x=>x.id} ListEmptyComponent={<Text style={s.muted}>No messages yet. Start the conversation.</Text>} renderItem={({item})=><View style={[s.msg,item.is_system&&s.system]}><Text style={s.content}>{item.content}</Text><View style={s.metaRow}><Text style={s.time}>{new Date(item.created_at).toLocaleString()}</Text>{item.is_read?<Text style={s.read}>Read</Text>:null}</View></View>}/>
  <View style={s.compose}><TextInput accessibilityLabel="Message" value={text} onChangeText={setText} placeholder="Write a message…" style={s.input} editable={!send.isPending}/><Pressable accessibilityRole="button" accessibilityState={{disabled:send.isPending}} disabled={send.isPending} onPress={submit} style={s.send}><Text style={s.sendText}>{send.isPending?'Sending…':'Send'}</Text></Pressable></View>
  {send.isError?<Text style={s.error}>Message could not be sent.</Text>:null}
 </View></Page>;
}
function Action({label,onPress,secondary=false}:{label:string;onPress:()=>void;secondary?:boolean}){return <Pressable accessibilityRole="button" onPress={onPress} style={[s.action,secondary&&s.secondary]}><Text style={[s.actionText,secondary&&s.secondaryText]}>{label}</Text></Pressable>}
const s=StyleSheet.create({wrap:{flex:1,gap:12},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'baseline'},title:{fontSize:30,fontWeight:'900',color:theme.colors.ink},sub:{fontSize:12,fontWeight:'700',color:theme.colors.muted},booking:{backgroundColor:'#fff',borderWidth:1,borderColor:theme.colors.line,borderRadius:18,padding:16,gap:8},bookingTitle:{fontSize:18,fontWeight:'800',color:theme.colors.ink},row:{flexDirection:'row',justifyContent:'space-between',gap:8},meta:{fontSize:12,color:theme.colors.muted},note:{fontStyle:'italic',color:theme.colors.muted},actions:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:6},action:{backgroundColor:theme.colors.ink,paddingHorizontal:13,paddingVertical:10,borderRadius:11},actionText:{color:'#fff',fontWeight:'800'},secondary:{backgroundColor:'#fff',borderWidth:1,borderColor:theme.colors.line},secondaryText:{color:theme.colors.ink},waiting:{color:theme.colors.muted,fontWeight:'700'},editor:{backgroundColor:theme.colors.canvas,borderRadius:16,padding:14,gap:10,borderWidth:1,borderColor:theme.colors.line},editorTitle:{fontSize:18,fontWeight:'800',color:theme.colors.ink},input:{flex:1,backgroundColor:'#fff',borderWidth:1,borderColor:theme.colors.line,borderRadius:12,padding:12,color:theme.colors.ink},messages:{flex:1},messageList:{paddingBottom:8},msg:{backgroundColor:'#fff',borderWidth:1,borderColor:theme.colors.line,borderRadius:14,padding:14,marginBottom:8},system:{backgroundColor:theme.colors.accentSoft},content:{color:theme.colors.ink,lineHeight:20},metaRow:{flexDirection:'row',justifyContent:'space-between',gap:8,marginTop:5},time:{fontSize:10,color:theme.colors.muted},read:{fontSize:10,fontWeight:'700',color:theme.colors.accent},compose:{flexDirection:'row',gap:8},send:{backgroundColor:theme.colors.ink,borderRadius:12,paddingHorizontal:16,justifyContent:'center'},sendText:{color:'#fff',fontWeight:'800'},error:{color:theme.colors.danger},muted:{color:theme.colors.muted},center:{flex:1,justifyContent:'center',alignItems:'center'}});