import{PropsWithChildren,ReactNode}from'react';import{Pressable,StyleSheet,Text,View}from'react-native';import{theme}from'./theme';

export function Button({label,onPress,secondary=false,disabled=false}:{label:string;onPress:()=>void;secondary?:boolean;disabled?:boolean}){return <Pressable accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={({pressed})=>[s.button,secondary&&s.buttonSecondary,disabled&&s.disabled,pressed&&s.pressed]}><Text style={[s.buttonText,secondary&&s.buttonTextSecondary]}>{label}</Text></Pressable>}
export function SectionTitle({title,action,onAction}:{title:string;action?:string;onAction?:()=>void}){return <View style={s.row}><Text style={s.section}>{title}</Text>{action&&onAction?<Pressable accessibilityRole="button" onPress={onAction}><Text style={s.action}>{action}</Text></Pressable>:null}</View>}
export function Card({children}:PropsWithChildren){return <View style={s.card}>{children}</View>}
export function StatusBadge({status}:{status:string}){const label=status.replaceAll('_',' ');return <View accessibilityLabel={label} style={s.badge}><Text style={s.badgeText}>{label}</Text></View>}
export function EmptyState({title,body}: {title:string;body?:string}){return <View style={s.state}><Text style={s.stateTitle}>{title}</Text>{body?<Text style={s.muted}>{body}</Text>:null}</View>}
export function ErrorState({title='Something went wrong',onRetry}:{title?:string;onRetry?:()=>void}){return <View style={s.state}><Text style={s.stateTitle}>{title}</Text>{onRetry?<Pressable accessibilityRole="button" onPress={onRetry}><Text style={s.action}>Try again</Text></Pressable>:null}</View>}
export function LoadingState({label='Loading…'}:{label?:string}){return <View style={s.state}><Text style={s.muted}>{label}</Text></View>}
export function InlineNotice({children}:PropsWithChildren){return <View style={s.notice}><Text style={s.muted}>{children}</Text></View>}
export function PriceBreakdown({basePrice,platformFee=0}:{basePrice:number;platformFee?:number}){const total=basePrice+platformFee;return <View style={s.price}><View style={s.row}><Text style={s.muted}>Service</Text><Text>{basePrice} credits</Text></View>{platformFee? <View style={s.row}><Text style={s.muted}>Platform fee</Text><Text>{platformFee} credits</Text></View>:null}<View style={[s.row,s.total]}><Text style={s.totalLabel}>Total</Text><Text style={s.totalValue}>{total} credits</Text></View></View>}
export function VisuallyHidden({children}:PropsWithChildren){return <Text style={{position:'absolute',width:1,height:1,opacity:0}}>{children as ReactNode}</Text>}

const s=StyleSheet.create({button:{backgroundColor:theme.colors.ink,borderRadius:theme.radius.md,paddingVertical:14,paddingHorizontal:18,alignItems:'center'},buttonSecondary:{backgroundColor:theme.colors.accentSoft},disabled:{opacity:.45},pressed:{opacity:.8},buttonText:{color:'#fff',fontWeight:'700',fontSize:16},buttonTextSecondary:{color:theme.colors.ink},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},section:{fontSize:22,fontWeight:'700',color:theme.colors.ink},action:{fontWeight:'700',color:theme.colors.accent},card:{backgroundColor:theme.colors.surface,padding:20,borderRadius:theme.radius.md,borderWidth:1,borderColor:theme.colors.line},badge:{alignSelf:'flex-start',paddingHorizontal:11,paddingVertical:6,borderRadius:99,backgroundColor:theme.colors.accentSoft},badgeText:{fontSize:12,fontWeight:'800',textTransform:'capitalize',color:theme.colors.ink},state:{paddingVertical:24,gap:8,alignItems:'center',justifyContent:'center'},stateTitle:{fontSize:18,fontWeight:'700',color:theme.colors.ink,textAlign:'center'},muted:{color:theme.colors.muted,lineHeight:22,textAlign:'center'},notice:{padding:14,borderRadius:theme.radius.sm,backgroundColor:theme.colors.accentSoft},price:{gap:8},total:{marginTop:6,paddingTop:10,borderTopWidth:1,borderTopColor:theme.colors.line},totalLabel:{fontWeight:'700'},totalValue:{fontWeight:'800',fontSize:18}});