import{useEffect,useState}from'react';import{ActivityIndicator,View}from'react-native';import{Stack,usePathname,useRouter}from'expo-router';import Head from'expo-router/head';import{QueryClient,QueryClientProvider}from'@tanstack/react-query';import{useAuth}from'../src/hooks/useAuth';import{getInitialNotificationUrl,subscribeToNotificationInteractions}from'../src/platform/notifications';

const protectedPrefixes=['/book/','/booking/','/bookings','/wallet','/messages','/message/','/profile','/locations','/notifications','/guruba-dashboard','/sign-in','/sign-up','/forgot-password','/reset-password'];
function isProtectedPath(pathname:string){return protectedPrefixes.some(prefix=>pathname===prefix||pathname.startsWith(prefix));}
function seoFor(pathname:string){if(pathname==='/')return{title:'Purohit — Spiritual Services in Nepal',description:'Discover verified Gurubas, explore spiritual services, check availability and book securely.'};if(pathname==='/discover')return{title:'Find a Guruba — Purohit',description:'Explore verified Gurubas and spiritual service providers through the Purohit network.'};if(pathname==='/services')return{title:'Spiritual Services — Purohit',description:'Browse Purohit spiritual services, duration, availability and credit pricing.'};if(pathname.startsWith('/guruba/'))return{title:'Verified Guruba — Purohit',description:'View a verified Guruba profile and available Purohit services.'};if(pathname.startsWith('/service/'))return{title:'Service Details — Purohit',description:'Explore this Purohit service, its duration, pricing and booking options.'};return{title:'Purohit',description:'Trusted spiritual services, made simple.'};}
function SessionGate(){
 const{session,loading}=useAuth();const pathname=usePathname();const router=useRouter();const protectedPath=isProtectedPath(pathname);const seo=seoFor(pathname);const canonicalPath=pathname==='/'?'':pathname;
 useEffect(()=>{if(!loading&&!session&&protectedPath)router.replace({pathname:'/sign-in',params:{redirect:pathname}})},[loading,session,protectedPath,pathname,router]);
 useEffect(()=>{if(loading)return;const open=(url:string)=>{if(session)router.push(url as never);else router.replace({pathname:'/sign-in',params:{redirect:url}})};getInitialNotificationUrl().then(url=>{if(url)open(url)}).catch(()=>{});return subscribeToNotificationInteractions(open)},[loading,session,router]);
 if(loading)return <View style={s.center}><ActivityIndicator/></View>;
 if(!session&&protectedPath)return <><Head><title>Sign in — Purohit</title><meta name="robots" content="noindex,nofollow"/></Head><View style={s.center}><ActivityIndicator/></View></>;
 return <><Head><title>{seo.title}</title><meta name="description" content={seo.description}/><meta name="robots" content={protectedPath?'noindex,nofollow':'index,follow'}/><link rel="canonical" href={`https://purohit.pages.dev${canonicalPath}`}/><meta property="og:title" content={seo.title}/><meta property="og:description" content={seo.description}/><meta property="og:url" content={`https://purohit.pages.dev${canonicalPath||'/' }`}/></Head><Stack screenOptions={{headerShown:false}}/></>;
}
export default function RootLayout(){const[queryClient]=useState(()=>new QueryClient({defaultOptions:{queries:{retry:1}}}));return <QueryClientProvider client={queryClient}><SessionGate/></QueryClientProvider>}
const s={center:{flex:1,justifyContent:'center' as const,alignItems:'center' as const}};