import{ActivityIndicator,Alert,Linking,Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import{useMemo,useState}from'react';
import{Link}from'expo-router';
import{useMutation,useQuery,useQueryClient}from'@tanstack/react-query';
import{supabase}from'../src/data/supabase';
import{useBookings,useCancelBooking,useRespondBookingTime}from'../src/hooks/useCoreData';
import{EmptyState,ErrorState,SectionTitle,StatusBadge}from'../src/ui/components';
import{Page}from'../src/ui/layout';
import{theme}from'../src/ui/theme';

type Filter='action'|'upcoming'|'history';
function formatWhen(value?:string|null){return value?new Date(value).toLocaleString():'Time to be confirmed'}
function sortTime(a:{scheduled_at?:string|null;proposed_time?:string|null;created_at?:string|null},b:{scheduled_at?:string|null;proposed_time?:string|null;created_at?:string|null}){return new Date(a.scheduled_at??a.proposed_time??a.created_at??0).getTime()-new Date(b.scheduled_at??b.proposed_time??b.created_at??0).getTime()}

export default function Bookings(){
 const q=useBookings();const respond=useRespondBookingTime();const cancel=useCancelBooking();const qc=useQueryClient();const[filter,setFilter]=useState<Filter>('upcoming');const[reviewing,setReviewing]=useState<string|null>(null);const[rating,setRating]=useState(5);const[comment,setComment]=useState('');
 const reviewedQ=useQuery({queryKey:['reviewed-bookings'],queryFn:async()=>{const{data,error}=await supabase.rpc('get_my_reviewed_booking_ids');if(error)throw error;return new Set((data??[]).map((x:any)=>x.booking_id as string))},enabled:!!q.data});
 const review=useMutation({mutationFn:async(v:{bookingId:string;rating:number;comment:string})=>{const{data,error}=await supabase.rpc('create_review',{p_booking_id:v.bookingId,p_rating:v.rating,p_comment:v.comment.trim()||null});if(error)throw error;return data},onSuccess:()=>{qc.invalidateQueries({queryKey:['reviewed-bookings']});setReviewing(null);setComment('');setRating(5)}});
 const rows=q.data??[];const reviewed=reviewedQ.data??new Set<string>();
 const counts=useMemo(()=>({action:rows.filter(b=>b.status==='awaiting_client_confirmation').length,upcoming:rows.filter(b=>['pending','confirmed','awaiting_client_confirmation','rescheduled'].includes(b.status)).length,history:rows.filter(b=>['completed','cancelled'].includes(b.status)).length}),[rows]);
 const visible=useMemo(()=>{let list=rows;if(filter==='action')list=rows.filter(b=>b.status==='awaiting_client_confirmation');if(filter==='history')list=rows.filter(b=>['completed','cancelled'].includes(b.status));if(filter==='upcoming')list=rows.filter(b=>['pending','confirmed','awaiting_client_confirmation','rescheduled'].includes(b.status));return[...list].sort(sortTime)},[rows,filter]);
 function confirmProposal(id:string){respond.mutate({id,accept:true})}
 function declineProposal(id:string){Alert.alert('Cancel booking','Reject this proposed time and cancel the booking?',[{text:'Keep booking'},{text:'Cancel booking',style:'destructive',onPress:()=>cancel.mutate(id)}])}
 function submitReview(id:string){review.mutate({bookingId:id,rating,comment})}
 return <Page><View style={s.header}><SectionTitle title="My bookings"/></View>
  {q.isLoading?<View style={s.center}><ActivityIndicator/><Text>Loading bookings…</Text></View>:q.isError?<ErrorState title="Unable to load your bookings" onRetry={q.refetch}/>:<ScrollView refreshControl={<RefreshControl refreshing={q.isFetching} onRefresh={q.refetch}/>} contentContainerStyle={s.container}>
   <View style={s.summary}><Metric label="Action required" value={counts.action}/><Metric label="Upcoming" value={counts.upcoming}/><Metric label="History" value={counts.history}/></View>
   <View style={s.filters}><FilterButton label={counts.action?'Action Required ('+counts.action+')':'Action Required'} active={filter==='action'} onPress={()=>setFilter('action')}/><FilterButton label={'Upcoming ('+counts.upcoming+')'} active={filter==='upcoming'} onPress={()=>setFilter('upcoming')}/><FilterButton label={'History ('+counts.history+')'} active={filter==='history'} onPress={()=>setFilter('history')}/></View>
   {!visible.length?<EmptyState title={filter==='action'?'Nothing needs your attention':filter==='history'?'No booking history yet':'No upcoming bookings'} body={filter==='upcoming'?'Choose a service and Guruba to make your next booking.':undefined}/>:visible.map(item=><View key={item.id} style={s.card}>
    <View style={s.row}><View style={s.grow}><Text style={s.title}>{item.services?.title??'Booking'}</Text><Text style={s.muted}>{item.gurubas?.full_name??'Guruba'}{item.gurubas?.location?' · '+item.gurubas.location:''}</Text></View><StatusBadge status={item.status}/></View>
    <View style={s.info}><Text style={s.label}>When</Text><Text style={s.value}>{formatWhen(item.scheduled_at??item.proposed_time)}</Text></View>
    <View style={s.split}><View style={s.info}><Text style={s.label}>Type</Text><Text style={s.value}>{item.is_online?'Online video':'Physical visit'}</Text></View><View style={s.info}><Text style={s.label}>Platform fee</Text><Text style={s.value}>{item.platform_fee??0} credits</Text></View></View>
    {item.location_address?<View style={s.info}><Text style={s.label}>Location</Text><Text style={s.value}>{item.location_address}</Text></View>:null}
    {item.booking_note?<View style={s.noteBox}><Text style={s.label}>Your note</Text><Text style={s.note}>{item.booking_note}</Text></View>:null}
    {item.status==='awaiting_client_confirmation'?<View style={s.actionBox}><Text style={s.actionTitle}>Guruba proposed a new time</Text><Text style={s.muted}>Confirm the proposed time to proceed, or cancel this booking.</Text><View style={s.actions}><ActionButton label="Confirm new time" onPress={()=>confirmProposal(item.id)}/><ActionButton label="Reject / cancel" secondary onPress={()=>declineProposal(item.id)}/></View></View>:null}
    {item.status==='confirmed'&&item.meeting_link?<ActionButton label="Join meeting" onPress={()=>Linking.openURL(item.meeting_link!)}/>:null}
    {item.status==='completed'&&!reviewed.has(item.id)?reviewing===item.id?<View style={s.reviewBox}><Text style={s.actionTitle}>Rate this ritual</Text><View style={s.stars}>{[1,2,3,4,5].map(n=><Pressable key={n} accessibilityRole="button" accessibilityState={{selected:rating===n}} onPress={()=>setRating(n)} style={[s.star,rating===n&&s.starActive]}><Text style={[s.starText,rating===n&&s.starTextActive]}>★ {n}</Text></Pressable>)}</View><TextInput value={comment} onChangeText={setComment} multiline placeholder="Optional comment…" style={s.comment}/><View style={s.actions}><ActionButton label={review.isPending?'Submitting…':'Submit review'} onPress={()=>submitReview(item.id)} disabled={review.isPending}/><ActionButton label="Cancel" secondary onPress={()=>setReviewing(null)}/></View>{review.isError?<Text style={s.error}>Review could not be submitted. Please try again.</Text>:null}</View>:<ActionButton label="Write a review" secondary onPress={()=>{setReviewing(item.id);setRating(5);setComment('')}}/>:<>{item.status==='completed'?<Text style={s.reviewed}>Review submitted</Text>:null}</>}
    <Link asChild href={{pathname:'/booking/[id]',params:{id:item.id}}}><Pressable accessibilityRole="button" style={s.details}><Text style={s.detailsText}>Open booking details →</Text></Pressable></Link>
   </View>)}
  </ScrollView>}
 </Page>
}
function Metric({label,value}:{label:string;value:number}){return <View style={s.metric}><Text style={s.metricValue}>{value}</Text><Text style={s.meta}>{label}</Text></View>}
function FilterButton({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable accessibilityRole="tab" accessibilityState={{selected:active}} onPress={onPress} style={[s.filter,active&&s.filterActive]}><Text style={[s.filterText,active&&s.filterTextActive]}>{label}</Text></Pressable>}
function ActionButton({label,onPress,secondary=false,disabled=false}:{label:string;onPress:()=>void;secondary?:boolean;disabled?:boolean}){return <Pressable accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={[s.action,secondary&&s.secondary,disabled&&s.disabled]}><Text style={[s.actionText,secondary&&s.secondaryText]}>{label}</Text></Pressable>}
const s=StyleSheet.create({header:{paddingTop:12,paddingBottom:4},container:{gap:12,paddingBottom:50},summary:{flexDirection:'row',flexWrap:'wrap',gap:10},metric:{flexGrow:1,minWidth:100,backgroundColor:'#fff',borderWidth:1,borderColor:theme.colors.line,borderRadius:16,padding:14},metricValue:{fontSize:25,fontWeight:'900',color:theme.colors.ink},meta:{fontSize:12,color:theme.colors.muted,marginTop:4},filters:{flexDirection:'row',flexWrap:'wrap',gap:8},filter:{paddingHorizontal:12,paddingVertical:10,borderRadius:999,borderWidth:1,borderColor:theme.colors.line,backgroundColor:'#fff'},filterActive:{backgroundColor:theme.colors.ink,borderColor:theme.colors.ink},filterText:{fontSize:12,fontWeight:'800',color:theme.colors.muted},filterTextActive:{color:'#fff'},card:{backgroundColor:'#fff',padding:18,borderRadius:18,borderWidth:1,borderColor:theme.colors.line,gap:10},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',gap:12},grow:{flex:1},title:{fontSize:18,fontWeight:'800',color:theme.colors.ink},muted:{color:theme.colors.muted,lineHeight:20},info:{gap:3},label:{fontSize:10,fontWeight:'800',letterSpacing:1,textTransform:'uppercase',color:theme.colors.muted},value:{fontSize:14,fontWeight:'700',color:theme.colors.ink},split:{flexDirection:'row',gap:18},noteBox:{padding:12,borderRadius:12,backgroundColor:theme.colors.canvas,gap:4},note:{fontSize:14,color:theme.colors.ink},actionBox:{padding:14,borderRadius:14,backgroundColor:theme.colors.accentSoft,borderWidth:1,borderColor:theme.colors.accent,gap:7},actionTitle:{fontSize:16,fontWeight:'800',color:theme.colors.ink},actions:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:4},action:{backgroundColor:theme.colors.ink,paddingHorizontal:13,paddingVertical:10,borderRadius:11},secondary:{backgroundColor:'#fff',borderWidth:1,borderColor:theme.colors.line},actionText:{color:'#fff',fontWeight:'800'},secondaryText:{color:theme.colors.ink},disabled:{opacity:.45},reviewBox:{padding:14,borderRadius:14,backgroundColor:theme.colors.canvas,gap:10},stars:{flexDirection:'row',flexWrap:'wrap',gap:6},star:{paddingHorizontal:9,paddingVertical:7,borderRadius:10,borderWidth:1,borderColor:theme.colors.line,backgroundColor:'#fff'},starActive:{backgroundColor:theme.colors.ink,borderColor:theme.colors.ink},starText:{fontSize:12,fontWeight:'800',color:theme.colors.muted},starTextActive:{color:'#fff'},comment:{minHeight:88,textAlignVertical:'top',backgroundColor:'#fff',borderWidth:1,borderColor:theme.colors.line,borderRadius:12,padding:12,color:theme.colors.ink},error:{color:theme.colors.danger},reviewed:{fontSize:12,fontWeight:'800',color:theme.colors.accent},details:{paddingVertical:5},detailsText:{fontWeight:'800',color:theme.colors.accent},center:{flex:1,justifyContent:'center',alignItems:'center',gap:10}});
