import{ActivityIndicator,FlatList,Image,Pressable,StyleSheet,Text,TextInput,View}from'react-native';
import{useMemo,useState}from'react';
import{Link}from'expo-router';
import{useGurubas}from'../src/hooks/useGurubas';
import{theme}from'../src/ui/theme';

type RatingFilter=0|4|4.5;

export default function Discover(){
 const q=useGurubas();const[search,setSearch]=useState('');const[rating,setRating]=useState<RatingFilter>(0);const[verifiedOnly,setVerifiedOnly]=useState(false);
 const rows=useMemo(()=>{const term=search.trim().toLowerCase();return(q.data??[]).filter(g=>{const hay=[g.full_name??'',g.location??'',...(g.specialties??[]),...(g.languages??[])].join(' ').toLowerCase();const textOk=!term||hay.includes(term);const ratingOk=rating===0||(g.rating??0)>=rating;const verifiedOk=!verifiedOnly||g.is_verified===true;return textOk&&ratingOk&&verifiedOk})},[q.data,search,rating,verifiedOnly]);
 if(q.isLoading)return <View style={s.center}><ActivityIndicator/><Text>Finding verified Gurubas…</Text></View>;
 if(q.isError)return <View style={s.center}><Text style={s.title}>Unable to load Gurubas</Text><Text style={s.muted}>Please retry from the previous screen.</Text></View>;
 return <FlatList data={rows} keyExtractor={x=>x.guruba_id} contentContainerStyle={s.list}
  ListHeaderComponent={<View style={s.header}><Text style={s.kicker}>DISCOVER</Text><Text style={s.title}>Find the right Guruba</Text><Text style={s.muted}>Search by name, location, specialty, or language.</Text><TextInput value={search} onChangeText={setSearch} placeholder="Search Guruba, puja, place…" style={s.search} autoCapitalize="none"/><View style={s.filters}><Chip label="All ratings" active={rating===0} onPress={()=>setRating(0)}/><Chip label="4+ rating" active={rating===4} onPress={()=>setRating(4)}/><Chip label="4.5+ rating" active={rating===4.5} onPress={()=>setRating(4.5)}/><Chip label="Verified only" active={verifiedOnly} onPress={()=>setVerifiedOnly(v=>!v)}/></View><Text style={s.resultCount}>{rows.length} Guruba{rows.length===1?'':'s'} found</Text></View>}
  ListEmptyComponent={<View style={s.empty}><Text style={s.emptyTitle}>No matching Gurubas</Text><Text style={s.muted}>Try a broader search or clear one of the filters.</Text><Pressable accessibilityRole="button" onPress={()=>{setSearch('');setRating(0);setVerifiedOnly(false)}} style={s.clear}><Text style={s.clearText}>Clear filters</Text></Pressable></View>}
  renderItem={({item})=><View style={s.card}>{item.avatar_url?<Image source={{uri:item.avatar_url}} style={s.avatar}/>:<View style={s.avatarFallback}><Text style={s.initial}>{(item.full_name??'G').slice(0,1).toUpperCase()}</Text></View>}<View style={s.cardBody}><View style={s.nameRow}><Text style={s.name}>{item.full_name??'Guruba'}</Text>{item.is_verified?<Text style={s.verified}>Verified</Text>:null}</View><Text style={s.meta}>{item.location??'Location not provided'}</Text>{item.rating!=null?<Text style={s.rating}>★ {item.rating.toFixed(1)} · {item.review_count??0} reviews</Text>:<Text style={s.meta}>New provider</Text>}{item.guruba_type?<Text style={s.meta}>{item.guruba_type}</Text>:null}{item.specialties?.length?<View style={s.tags}>{item.specialties.slice(0,5).map(x=><Text key={x} style={s.tag}>{x}</Text>)}</View>:null}<Link href={{pathname:'/guruba/[id]',params:{id:item.guruba_id}}} style={s.view}>View Guruba →</Link></View></View>}
 />
}
function Chip({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable accessibilityRole="button" accessibilityState={{selected:active}} onPress={onPress} style={[s.chip,active&&s.chipActive]}><Text style={[s.chipText,active&&s.chipTextActive]}>{label}</Text></Pressable>}
const s=StyleSheet.create({list:{padding:20,gap:12,backgroundColor:theme.colors.canvas,minHeight:'100%',paddingBottom:40},header:{gap:10,paddingBottom:4},kicker:{fontSize:11,fontWeight:'800',letterSpacing:1.5,color:theme.colors.muted},title:{fontSize:30,fontWeight:'900',color:theme.colors.ink},muted:{color:theme.colors.muted,lineHeight:20},search:{backgroundColor:'#fff',borderWidth:1,borderColor:theme.colors.line,borderRadius:14,padding:13,color:theme.colors.ink},filters:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{paddingHorizontal:12,paddingVertical:9,borderRadius:999,borderWidth:1,borderColor:theme.colors.line,backgroundColor:'#fff'},chipActive:{backgroundColor:theme.colors.ink,borderColor:theme.colors.ink},chipText:{fontWeight:'700',color:theme.colors.muted,fontSize:12},chipTextActive:{color:'#fff'},resultCount:{fontSize:12,fontWeight:'800',color:theme.colors.muted},card:{backgroundColor:'#fff',borderWidth:1,borderColor:theme.colors.line,borderRadius:18,padding:16,flexDirection:'row',gap:14},avatar:{width:62,height:62,borderRadius:31,backgroundColor:theme.colors.canvas},avatarFallback:{width:62,height:62,borderRadius:31,backgroundColor:theme.colors.canvas,alignItems:'center',justifyContent:'center'},initial:{fontSize:24,fontWeight:'900',color:theme.colors.ink},cardBody:{flex:1,gap:5},nameRow:{flexDirection:'row',alignItems:'center',gap:8},name:{fontSize:18,fontWeight:'800',color:theme.colors.ink,flexShrink:1},verified:{fontSize:10,fontWeight:'800',color:theme.colors.ink,borderWidth:1,borderColor:theme.colors.line,borderRadius:999,paddingHorizontal:7,paddingVertical:3},meta:{color:theme.colors.muted,fontSize:12},rating:{fontWeight:'800',color:theme.colors.ink,fontSize:13},tags:{flexDirection:'row',flexWrap:'wrap',gap:6,marginTop:3},tag:{fontSize:11,color:theme.colors.muted,borderWidth:1,borderColor:theme.colors.line,borderRadius:999,paddingHorizontal:8,paddingVertical:4},view:{alignSelf:'flex-start',marginTop:5,color:theme.colors.ink,fontWeight:'800'},empty:{alignItems:'center',padding:40,gap:8},emptyTitle:{fontSize:18,fontWeight:'800',color:theme.colors.ink},clear:{marginTop:6,paddingHorizontal:14,paddingVertical:10,borderRadius:10,backgroundColor:theme.colors.ink},clearText:{color:'#fff',fontWeight:'800'},center:{flex:1,justifyContent:'center',alignItems:'center',padding:30},titleSmall:{fontSize:18,fontWeight:'800'}});
