import{ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,View}from'react-native';
import{useMemo}from'react';
import{Link}from'expo-router';
import{useQuery}from'@tanstack/react-query';
import{useAuth}from'../src/hooks/useAuth';
import{api}from'../src/data/contracts';
import{theme}from'../src/ui/theme';

function formatDate(value?:string|null){return value?new Date(value).toLocaleString():'Not scheduled'}

export default function Home(){
 const{session,loading}=useAuth();
 const profile=useQuery({queryKey:['home-profile'],queryFn:api.getMyProfile,enabled:!!session});
 const bookings=useQuery({queryKey:['home-bookings'],queryFn:()=>api.getMyBookings('client'),enabled:!!session,refetchInterval:30000,refetchIntervalInBackground:false});
 const upcoming=useMemo(()=>{const rows=(bookings.data??[]).filter(b=>['pending','confirmed','awaiting_client_confirmation','rescheduled'].includes(b.status));return rows.sort((a,b)=>new Date(a.scheduled_at??a.proposed_time??a.created_at??0).getTime()-new Date(b.scheduled_at??b.proposed_time??b.created_at??0).getTime()).slice(0,3)},[bookings.data]);
 const actionRequired=(bookings.data??[]).filter(b=>b.status==='awaiting_client_confirmation');
 if(loading)return <View style={s.center}><ActivityIndicator/></View>;
 if(!session)return <ScrollView contentContainerStyle={s.container}><View style={s.hero}><Text style={s.kicker}>PUROHIT</Text><Text style={s.title}>Trusted spiritual services, made simple.</Text><Text style={s.body}>Discover verified Gurubas, choose a service, see live availability and book securely.</Text><View style={s.actions}><Link href="/discover" style={s.primary}>Find a Guruba</Link><Link href="/services" style={s.secondary}>Browse services</Link></View></View><View style={s.grid}><Link href="/discover" style={s.card}><Text style={s.cardTitle}>Find a Guruba</Text><Text style={s.bodySmall}>Explore verified providers</Text></Link><Link href="/services" style={s.card}><Text style={s.cardTitle}>Browse services</Text><Text style={s.bodySmall}>See duration and credits</Text></Link><Link href="/sign-in" style={s.card}><Text style={s.cardTitle}>Sign in</Text><Text style={s.bodySmall}>Manage bookings, wallet and messages</Text></Link></View></ScrollView>;
 if(profile.isLoading||bookings.isLoading)return <View style={s.center}><ActivityIndicator/><Text>Loading your Purohit workspace…</Text></View>;
 const p=profile.data;const rows=bookings.data??[];const completed=rows.filter(b=>b.status==='completed').length;const confirmed=rows.filter(b=>b.status==='confirmed').length;
 return <ScrollView contentContainerStyle={s.container}><View style={s.heroSmall}><Text style={s.kicker}>MY PUROHIT</Text><Text style={s.titleSmall}>Namaste, {p?.full_name||'there'} 🙏</Text><Text style={s.body}>Your spiritual journey at a glance.</Text></View>
  {actionRequired.length>0?<View style={s.alert}><Text style={s.alertTitle}>Action required</Text><Text style={s.alertBody}>{actionRequired.length} booking{actionRequired.length===1?'':'s'} need your confirmation.</Text><Link href="/bookings" style={s.alertLink}>Review booking{actionRequired.length===1?'':'s'} →</Link></View>:null}
  <View style={s.metrics}><Metric label="Total bookings" value={rows.length}/><Metric label="Confirmed" value={confirmed}/><Metric label="Completed rituals" value={completed}/><Metric label="Available credits" value={p?.credits??0}/></View>
  <View style={s.section}><View style={s.sectionHeader}><Text style={s.sectionTitle}>Upcoming schedule</Text><Link href="/bookings" style={s.link}>View all</Link></View>{upcoming.length?upcoming.map(b=><View key={b.id} style={s.bookingCard}><View style={{flex:1}}><Text style={s.bookingTitle}>{b.services?.title??'Booking'}</Text><Text style={s.muted}>{b.gurubas?.full_name??'Guruba'}</Text><Text style={s.meta}>{formatDate(b.scheduled_at??b.proposed_time)} · {b.is_online?'Online':'Physical'}</Text></View><Text style={s.status}>{b.status.replaceAll('_',' ')}</Text></View>):<Text style={s.muted}>No upcoming rituals. Time to book one.</Text>}</View>
  <View style={s.quick}><Text style={s.sectionTitle}>Quick actions</Text><View style={s.grid}><Link href="/discover" style={s.card}><Text style={s.cardTitle}>Find a Guruba</Text><Text style={s.bodySmall}>Explore verified providers</Text></Link><Link href="/services" style={s.card}><Text style={s.cardTitle}>Browse services</Text><Text style={s.bodySmall}>Compare rituals and pricing</Text></Link><Link href="/wallet" style={s.card}><Text style={s.cardTitle}>Wallet</Text><Text style={s.bodySmall}>{p?.credits??0} credits available</Text></Link><Link href="/messages" style={s.card}><Text style={s.cardTitle}>Messages</Text><Text style={s.bodySmall}>Talk to your Guruba</Text></Link><Link href="/profile" style={s.card}><Text style={s.cardTitle}>Profile</Text><Text style={s.bodySmall}>Account and saved locations</Text></Link>{p?.role==='guruba'?<Link href="/guruba-dashboard" style={s.card}><Text style={s.cardTitle}>Guruba workspace</Text><Text style={s.bodySmall}>Manage requests and availability</Text></Link>:null}</View></View>
 </ScrollView>
}
function Metric({label,value}:{label:string;value:number}){return <View style={s.metric}><Text style={s.metricValue}>{value}</Text><Text style={s.meta}>{label}</Text></View>}
const s=StyleSheet.create({container:{backgroundColor:theme.colors.canvas,minHeight:'100%',padding:24,gap:16,paddingBottom:50},hero:{maxWidth:900,width:'100%',alignSelf:'center',paddingVertical:48,gap:4},heroSmall:{maxWidth:900,width:'100%',alignSelf:'center',paddingVertical:18,gap:4},kicker:{fontSize:12,fontWeight:'800',letterSpacing:2,color:theme.colors.accent},title:{fontSize:42,lineHeight:50,fontWeight:'800',color:theme.colors.ink,marginTop:6},titleSmall:{fontSize:34,lineHeight:40,fontWeight:'900',color:theme.colors.ink,marginTop:6},body:{fontSize:17,lineHeight:26,color:theme.colors.muted,marginTop:8},actions:{flexDirection:'row',flexWrap:'wrap',gap:10,marginTop:18},primary:{backgroundColor:theme.colors.ink,color:'#fff',paddingHorizontal:18,paddingVertical:13,borderRadius:12,fontWeight:'800'},secondary:{backgroundColor:'#fff',color:theme.colors.ink,paddingHorizontal:18,paddingVertical:13,borderRadius:12,borderWidth:1,borderColor:theme.colors.line,fontWeight:'800'},grid:{maxWidth:900,width:'100%',alignSelf:'center',flexDirection:'row',flexWrap:'wrap',gap:12},card:{flexGrow:1,minWidth:220,backgroundColor:'#fff',padding:18,borderRadius:16,borderWidth:1,borderColor:theme.colors.line},cardTitle:{fontSize:18,fontWeight:'800',color:theme.colors.ink},bodySmall:{fontSize:13,lineHeight:19,color:theme.colors.muted,marginTop:4},alert:{maxWidth:900,width:'100%',alignSelf:'center',backgroundColor:theme.colors.accentSoft,borderWidth:1,borderColor:theme.colors.accent,borderRadius:16,padding:16,gap:5},alertTitle:{fontSize:17,fontWeight:'900',color:theme.colors.ink},alertBody:{color:theme.colors.muted},alertLink:{alignSelf:'flex-start',fontWeight:'800',color:theme.colors.accent,marginTop:4},metrics:{maxWidth:900,width:'100%',alignSelf:'center',flexDirection:'row',flexWrap:'wrap',gap:10},metric:{flexGrow:1,minWidth:150,minHeight:96,backgroundColor:'#fff',borderWidth:1,borderColor:theme.colors.line,borderRadius:16,padding:16,justifyContent:'center'},metricValue:{fontSize:28,fontWeight:'900',color:theme.colors.ink},meta:{fontSize:12,color:theme.colors.muted,marginTop:4},section:{maxWidth:900,width:'100%',alignSelf:'center',backgroundColor:'#fff',borderWidth:1,borderColor:theme.colors.line,borderRadius:18,padding:18,gap:12},sectionHeader:{flexDirection:'row',justifyContent:'space-between',alignItems:'baseline'},sectionTitle:{fontSize:20,fontWeight:'800',color:theme.colors.ink},link:{fontWeight:'800',color:theme.colors.accent},bookingCard:{flexDirection:'row',alignItems:'center',gap:12,borderTopWidth:1,borderTopColor:theme.colors.line,paddingTop:12},bookingTitle:{fontSize:16,fontWeight:'800',color:theme.colors.ink},muted:{color:theme.colors.muted,lineHeight:20},status:{fontSize:11,fontWeight:'800',color:theme.colors.ink,textTransform:'uppercase',maxWidth:90,textAlign:'right'},quick:{maxWidth:900,width:'100%',alignSelf:'center',gap:12},center:{flex:1,justifyContent:'center',alignItems:'center',gap:10,backgroundColor:theme.colors.canvas}});
