import{Alert,ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import{useMemo,useState}from'react';
import{Link,router}from'expo-router';
import{supabase}from'../src/data/supabase';
import{useApprovedGotras,useDeleteLocation,useProfile,useRequestGotra,useSavedLocations,useSaveLocation,useUpdateProfile}from'../src/hooks/useCoreData';
import{Page}from'../src/ui/layout';
import{theme}from'../src/ui/theme';

export default function Profile(){
 const q=useProfile();const gotrasQ=useApprovedGotras();const locationsQ=useSavedLocations();const update=useUpdateProfile();const requestGotra=useRequestGotra();const saveLoc=useSaveLocation();const deleteLoc=useDeleteLocation();
 const p=q.data;const[editing,setEditing]=useState(false);const[name,setName]=useState('');const[phone,setPhone]=useState('');const[city,setCity]=useState('');const[gotra,setGotra]=useState('');const[languages,setLanguages]=useState('');const[gotraSearch,setGotraSearch]=useState('');const[newLoc,setNewLoc]=useState<{name:string;address:string;lat:string;lng:string}|null>(null);
 const filteredGotras=useMemo(()=>{const t=gotraSearch.trim().toLowerCase();return(gotrasQ.data??[]).filter(g=>!t||g.name.toLowerCase().includes(t)).slice(0,8)},[gotrasQ.data,gotraSearch]);
 function beginEdit(){setName(p?.full_name??'');setPhone(p?.phone??'');setCity(p?.city??'');setGotra(p?.gotra_id??'');setLanguages((p?.languages??[]).join(', '));setEditing(true)}
 async function save(){try{await update.mutateAsync({fullName:name.trim(),phone:phone.trim(),city:city.trim(),gotraId:gotra||null,languages:languages.split(',').map(x=>x.trim()).filter(Boolean)});Alert.alert('Saved','Profile updated.');setEditing(false)}catch(e:any){Alert.alert('Save failed',e?.message??'Unable to update profile.')}}
 async function requestNewGotra(){const n=gotraSearch.trim();if(!n)return;try{const id=await requestGotra.mutateAsync(n);setGotra(id);Alert.alert('Requested','Gotra request submitted for approval.')}catch(e:any){Alert.alert('Request failed',e?.message??'Unable to submit request.')}}
 async function saveLocation(){if(!newLoc)return;const lat=Number(newLoc.lat),lng=Number(newLoc.lng);if(!newLoc.name.trim()||!Number.isFinite(lat)||!Number.isFinite(lng)){Alert.alert('Invalid location','Enter a name and valid latitude/longitude.');return}try{await saveLoc.mutateAsync({name:newLoc.name.trim(),lat,lng,address:newLoc.address.trim()});setNewLoc(null);Alert.alert('Saved','Location added to your saved locations.')}catch(e:any){Alert.alert('Save failed',e?.message??'Unable to save location.')}}
 if(q.isLoading)return <View style={s.center}><ActivityIndicator/></View>;
 if(!p)return <Page><Text style={s.title}>Profile unavailable</Text></Page>;
 return <Page><ScrollView contentContainerStyle={s.wrap}>
  <View style={s.header}><View style={{flex:1}}><Text style={s.kicker}>ACCOUNT</Text><Text style={s.title}>{p.full_name||'My profile'}</Text><Text style={s.muted}>{p.email}</Text></View><Pressable accessibilityRole="button" onPress={editing?()=>setEditing(false):beginEdit} style={s.edit}><Text style={s.editText}>{editing?'Cancel':'Edit'}</Text></Pressable></View>
  {editing?<View style={s.card}><Field label="Full name" value={name} onChangeText={setName}/><Field label="Phone" value={phone} onChangeText={setPhone} keyboardType="phone-pad"/><Field label="City" value={city} onChangeText={setCity}/><Field label="Languages" value={languages} onChangeText={setLanguages} placeholder="Nepali, Sanskrit, English"/><Text style={s.label}>Gotra</Text><TextInput value={gotraSearch} onChangeText={setGotraSearch} placeholder="Search gotra…" style={s.input}/>{filteredGotras.map(g=><Pressable key={g.id} onPress={()=>{setGotra(g.id);setGotraSearch(g.name)}} style={[s.option,gotra===g.id&&s.optionActive]}><Text style={s.optionText}>{g.name}</Text></Pressable>)}{gotraSearch.trim()&&!filteredGotras.some(g=>g.name.toLowerCase()===gotraSearch.trim().toLowerCase())?<Pressable onPress={requestNewGotra} disabled={requestGotra.isPending} style={s.request}><Text style={s.requestText}>{requestGotra.isPending?'Requesting…':'Request this gotra'}</Text></Pressable>:null}<Pressable disabled={update.isPending} onPress={save} style={s.button}><Text style={s.buttonText}>{update.isPending?'Saving…':'Save profile'}</Text></Pressable></View>:<View style={s.card}><Info label="City" value={p.city||'Not set'}/><Info label="Phone" value={p.phone||'Not set'}/><Info label="Gotra" value={(gotrasQ.data??[]).find(g=>g.id===p.gotra_id)?.name||p.gotra_id||'Not set'}/><Info label="Languages" value={(p.languages??[]).join(', ')||'Not set'}/></View>}
  <View style={s.card}><View style={s.row}><Text style={s.section}>Saved locations</Text><Pressable onPress={()=>setNewLoc({name:'',address:'',lat:'27.7172',lng:'85.3240'})}><Text style={s.link}>Add</Text></Pressable></View>{locationsQ.isLoading?<ActivityIndicator/>:locationsQ.data?.length?locationsQ.data.map(l=><View key={l.id} style={s.location}><View style={{flex:1}}><Text style={s.name}>{l.name}</Text><Text style={s.muted}>{l.address||String(l.latitude)+', '+String(l.longitude)}</Text></View><Pressable accessibilityRole="button" onPress={()=>deleteLoc.mutate(l.id)}><Text style={s.remove}>Delete</Text></Pressable></View>):<Text style={s.muted}>No saved locations yet.</Text>}{newLoc&&<View style={s.addBox}><Field label="Name" value={newLoc.name} onChangeText={v=>setNewLoc({...newLoc,name:v})} placeholder="Home"/><Field label="Address" value={newLoc.address} onChangeText={v=>setNewLoc({...newLoc,address:v})} placeholder="Kathmandu"/><View style={s.row}><TextInput value={newLoc.lat} onChangeText={v=>setNewLoc({...newLoc,lat:v})} keyboardType="decimal-pad" placeholder="Latitude" style={s.half}/><TextInput value={newLoc.lng} onChangeText={v=>setNewLoc({...newLoc,lng:v})} keyboardType="decimal-pad" placeholder="Longitude" style={s.half}/></View><View style={s.actions}><Pressable onPress={()=>setNewLoc(null)} style={s.secondary}><Text style={s.secondaryText}>Cancel</Text></Pressable><Pressable disabled={saveLoc.isPending} onPress={saveLocation} style={s.button}><Text style={s.buttonText}>{saveLoc.isPending?'Saving…':'Save location'}</Text></Pressable></View></View>}</View>
  <View style={s.links}><Link href="/wallet" style={s.link}>Wallet & ledger</Link><Link href="/notifications" style={s.link}>Notifications</Link>{p.role==='guruba'?<Link href="/guruba-dashboard" style={s.link}>Guruba workspace</Link>:null}</View>
  <Pressable onPress={async()=>{await supabase.auth.signOut();router.replace('/')}}><Text style={s.signout}>Sign out</Text></Pressable>
 </ScrollView></Page>
}
function Field({label,value,onChangeText,placeholder='',multiline=false,keyboardType}:{label:string;value:string;onChangeText:(v:string)=>void;placeholder?:string;multiline?:boolean;keyboardType?:any}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder||label} multiline={multiline} keyboardType={keyboardType} style={[s.input,multiline&&s.textarea]}/></View>}
function Info({label,value}:{label:string;value:string}){return <View style={s.info}><Text style={s.label}>{label}</Text><Text style={s.value}>{value}</Text></View>}
const s=StyleSheet.create({wrap:{gap:14,paddingBottom:48},header:{flexDirection:'row',alignItems:'flex-start',gap:12},kicker:{fontSize:11,fontWeight:'800',letterSpacing:1.5,color:theme.colors.muted},title:{fontSize:30,fontWeight:'900',color:theme.colors.ink},muted:{color:theme.colors.muted,lineHeight:20},card:{backgroundColor:'#fff',borderWidth:1,borderColor:theme.colors.line,borderRadius:18,padding:18,gap:12},edit:{paddingHorizontal:13,paddingVertical:9,borderWidth:1,borderColor:theme.colors.line,borderRadius:10},editText:{fontWeight:'800',color:theme.colors.ink},field:{gap:6},label:{fontSize:11,fontWeight:'800',textTransform:'uppercase',color:theme.colors.muted},input:{backgroundColor:'#fff',borderWidth:1,borderColor:theme.colors.line,borderRadius:12,padding:12,color:theme.colors.ink},textarea:{minHeight:100,textAlignVertical:'top'},option:{padding:10,borderRadius:10},optionActive:{backgroundColor:theme.colors.canvas},optionText:{fontWeight:'700',color:theme.colors.ink},request:{padding:12,borderRadius:10,backgroundColor:theme.colors.canvas},requestText:{fontWeight:'800',color:theme.colors.ink},button:{alignSelf:'flex-start',backgroundColor:theme.colors.ink,paddingHorizontal:15,paddingVertical:11,borderRadius:11},buttonText:{fontWeight:'800',color:'#fff'},secondary:{alignSelf:'flex-start',paddingHorizontal:15,paddingVertical:11,borderRadius:11,borderWidth:1,borderColor:theme.colors.line},secondaryText:{fontWeight:'800',color:theme.colors.ink},row:{flexDirection:'row',alignItems:'center',gap:10},section:{fontSize:19,fontWeight:'800',color:theme.colors.ink,flex:1},link:{fontWeight:'800',color:theme.colors.accent},location:{flexDirection:'row',gap:10,alignItems:'center',paddingVertical:10,borderTopWidth:1,borderTopColor:theme.colors.line},name:{fontWeight:'800',color:theme.colors.ink},remove:{fontWeight:'800',color:theme.colors.danger},addBox:{marginTop:4,padding:14,borderRadius:14,backgroundColor:theme.colors.canvas,gap:10},half:{flex:1,backgroundColor:'#fff',borderWidth:1,borderColor:theme.colors.line,borderRadius:12,padding:12},actions:{flexDirection:'row',gap:8},info:{paddingVertical:4},value:{fontSize:16,fontWeight:'700',color:theme.colors.ink},links:{gap:10,paddingTop:4},signout:{fontWeight:'800',color:theme.colors.danger},center:{flex:1,justifyContent:'center',alignItems:'center'}});
