import{useMutation,useQuery,useQueryClient}from'@tanstack/react-query';import type{Service}from'../data/contracts';import*as api from'../data/contracts';
export const useProfile=()=>useQuery({queryKey:['profile'],queryFn:api.api.getMyProfile});
export const useServices=()=>useQuery({queryKey:['services'],queryFn:api.api.getPublicServices,staleTime:300000});
export const useService=(id?:string)=>{const q=useServices();return{...q,data:q.data?.find(x=>x.id===id)}};
export const useBookingOptions=(id?:string)=>useQuery({queryKey:['booking-options',id],queryFn:()=>api.api.getBookingOptions(id!),enabled:!!id,staleTime:60000});
export const useGuruba=(id?:string)=>useQuery({queryKey:['guruba',id],queryFn:async()=>{const rows=await api.api.getPublicGurubas();return rows.find(x=>x.guruba_id===id)??null},enabled:!!id,staleTime:60000});
export const useGurubaServices=(id?:string)=>useQuery({queryKey:['guruba-services-public',id],queryFn:async()=>{const services=await api.api.getPublicServices();const pairs=await Promise.all(services.map(async service=>{const rows=await api.api.getBookingOptions(service.id) as any[];const match=rows.find(x=>x.guruba_id===id);return match?{service,option:match}:null}));return pairs.filter(Boolean) as {service:Service;option:any}[]},enabled:!!id,staleTime:60000});
export const useBookings=(role:'client'|'guruba'='client')=>useQuery({queryKey:['bookings',role],queryFn:()=>api.api.getMyBookings(role),refetchInterval:role==='guruba'?15000:30000,refetchIntervalInBackground:false});
export const useTransactions=()=>useQuery({queryKey:['transactions'],queryFn:api.api.getMyTransactions});
export const useSavedLocations=()=>useQuery({queryKey:['locations'],queryFn:api.api.getMySavedLocations});
export const useMessageUsers=()=>useQuery({queryKey:['message-users'],queryFn:api.api.getMessageUsers,refetchInterval:30000});
export const useMessages=(id?:string,b?:string)=>useQuery({queryKey:['messages',id,b],queryFn:()=>api.api.getMessages(id!,b),enabled:!!id,refetchInterval:15000,refetchIntervalInBackground:false});
export const useNotifications=()=>useQuery({queryKey:['notifications'],queryFn:api.api.getMyNotifications,staleTime:30000});
export const useBookingSlots=(g?:string,s?:string,d?:string)=>useQuery({queryKey:['slots',g,s,d],queryFn:()=>api.api.getAvailableSlots(g!,s!,d!),enabled:!!g&&!!s&&!!d});
export const useGurubaProfile=()=>useQuery({queryKey:['guruba-profile'],queryFn:api.api.getMyGurubaProfile});
export const useGurubaServicesSelf=()=>useQuery({queryKey:['guruba-services'],queryFn:api.api.getMyGurubaServices});
export const useAvailability=()=>useQuery({queryKey:['availability'],queryFn:api.api.getMyAvailability});
const mutate=(fn:any,keys:string[][])=>{const q=useQueryClient();return useMutation({mutationFn:fn,onSuccess:()=>keys.forEach(k=>q.invalidateQueries({queryKey:k}))})};
export const useBookService=()=>mutate(api.api.bookService,[['bookings']]);
export const useConfirmBooking=()=>mutate(api.api.confirmBooking,[['bookings']]);
export const useProposeBookingTime=()=>mutate(({id,at,deadline}:{id:string;at:string;deadline?:string})=>api.api.proposeBookingTime(id,at,deadline),[['bookings']]);
export const useRespondBookingTime=()=>mutate(({id,accept}:{id:string;accept:boolean})=>api.api.respondBookingTime(id,accept),[['bookings']]);
export const useCancelBooking=()=>mutate(api.api.cancelBooking,[['bookings'],['transactions']]);
export const useCompleteBooking=()=>mutate(api.api.completeBooking,[['bookings']]);
export const useRescheduleBooking=()=>mutate(({id,at}:{id:string;at:string})=>api.api.rescheduleBooking(id,at),[['bookings']]);
export const useSetBookingMeetingLink=()=>mutate(({id,link}:{id:string;link:string})=>api.api.setBookingMeetingLink(id,link),[['bookings']]);
export const useRequestTopup=()=>mutate(api.api.requestTopup,[['transactions']]);
export const useSaveLocation=()=>mutate(({name,lat,lng,address}:{name:string;lat:number;lng:number;address?:string})=>api.api.saveLocation(name,lat,lng,address),[['locations']]);
export const useDeleteLocation=()=>mutate(api.api.deleteLocation,[['locations']]);
export const useSendMessage=()=>{const q=useQueryClient();return useMutation({mutationFn:({receiverId,content,bookingId}:{receiverId:string;content:string;bookingId?:string})=>api.api.sendMessage(receiverId,content,bookingId),onSuccess:(_,v)=>{q.invalidateQueries({queryKey:['messages',v.receiverId]});q.invalidateQueries({queryKey:['message-users']})}})};
export const useMarkMessagesRead=()=>mutate(api.api.markMessagesRead,[['messages'],['message-users']]);
export const useMarkNotificationRead=()=>mutate(api.api.markNotificationRead,[['notifications']]);
export const useUpsertGurubaProfile=()=>mutate(api.api.upsertGurubaProfile,[['guruba-profile'],['profile']]);
export const useSetGurubaService=()=>mutate(({serviceId,enabled,online}:{serviceId:string;enabled:boolean;online:boolean})=>api.api.setGurubaService(serviceId,enabled,online),[['guruba-services']]);
export const useSetAvailability=()=>mutate(({day,start,end}:{day:number;start:string;end:string})=>api.api.setAvailability(day,start,end),[['availability']]);
export const useDeleteAvailability=()=>mutate(api.api.deleteAvailability,[['availability']]);
